CaravanCamels:
  type : obs
  stream_id: 2
  filenames : ['/e/project1/e-aif-2026sc02-173/sk_data/inflow_nordics_obs.zarr']
  base_datetime : '2001-01-01T00:00:00'
  coords_channels : ['lat', 'lon']
  target:
    - 'obsvalue_streamflow_0'
  geoinfo_channels:
    - 'area'
    - 'slp_dg_sav'
    - 'ele_mt_sav'
    - 'ele_mt_smn'
    - 'ele_mt_smx'
    - 'frac_snow'

    #- 'low_prec_dur'
    #- 'high_prec_freq'
    #- 'high_prec_dur'
    #- 'low_prec_freq'
    #- 'p_mean'
    #- 'urb_pc_sse'
    #- 'for_pc_sse'
    #- 'gla_pc_sse'
    #- 'snd_pc_sav'
    #- 'ire_pc_sse'
    #- 'ari_ix_sav'
    #- 'cmi_ix_syr'
    #- 'pet_mean_ERA5_LAND'
    #- 'seasonality_ERA5_LAND'
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 8
  tokenize_spacetime : True    
  max_num_targets: -1
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 8
    dim_embed : 512
    num_blocks : 2
  embed_target_coords : 
    net : linear
    dim_embed : 512
  target_readout :
    num_layers : 2
    num_heads : 4
  pred_head : 
    ens_size : 1
    num_layers : 1


#    - 'eccentricity'
#    - 'area'
#    - 'ele_mt_smn'
#    - 'ele_mt_smx'
#    - 'ele_mt_sav'
#    - 'elev_median'
#    - 'elev_std'
#    - 'slope_max'
#    - 'slp_dg_sav'
#    - 'slope_median'
#    - 'slope_std'
#    - 'urb_pc_sse'
#    - 'agriculture_frac'
#    - 'for_pc_sse'
#    - 'grassland_frac'
#    - 'moors_and_heathland_frac'
#    - 'woodland_shrubs_frac'
#    - 'snd_pc_sav'
#    - 'ire_pc_sse'
#    - 'sparsely_vegetated_frac'
#    - 'gla_pc_sse'
#    - 'peat_bogs_and_marshes_frac'
#    - 'water_bodies_frac'
#    - 'p_mean'
#    - 'pet_mean_ERA5_LAND'
#    - 'ari_ix_sav'
#    - 'frac_snow'
#    - 'cmi_ix_syr'
#    - 'seasonality_ERA5_LAND'
#    - 'high_prec_freq'
#    - 'high_prec_dur'
#    - 'low_prec_freq'
#    - 'low_prec_dur'
#    - 'QA_internal'
#    - 'QA_value'
#    - 'Regulated'
